Generete new artifact and update the dejave execution bash file

diff --git a/out/dejavu b/out/dejavu
--- a/out/dejavu
+++ b/out/dejavu
@@ -5,29 +5,117 @@
 #
 # To use, call (after making executable with: chmod +x dejavu) as follows:
 #
-#   dejavu <specFile> <traceFile> [<bitsPerVariable> [debug]]
+#   dejavu (--specfile=<filename>) (--logfile=<filename>) [--bits=numOfBits] [--mode=(debug | profile)]
+#          [--prediction=num] [--prediction_type=(smart | brute)] [--clear=(0 | 1)]
+#
+#   Options:
+#     -s, --specfile          the path to a file containing the specification document. This is a mandatory field.
+#     -l, --logfile           the path to a file containing the log in CSV format to be analyzed.
+#     -b, --bits              number indicating how many bits should be assigned to each variable in the BDD representation. If nothing is specified, the default value is 20 bits.
+#     -m, --mode              specifies output modes. by default no one is active.
+#     -p, --prediction        indicates whether prediction is required, along with the size of the prediction parameters.
+#     -t, --prediction_type   specifies prediction approach. by default smart approach is activated.
+#     -c, --clear             indicating whether to clear generated files and folder. value of '1' is for cleaning.
 
-BDDSIZE=${3:-20} # default number of bits per variable = 20
-DEBUG=${4:-} # default is no debugging
 
-echo ""
-echo "BDD bits per variable = $BDDSIZE" 
-echo $DEBUG
+for i in "$@"; do
+  echo "${i}"
+  case $i in
+    -s=*|--specfile=*)
+      SPECFILE="${i#*=}"
+      shift # past argument=value
+      ;;
+    -l=*|--logfile=*)
+      LOGFILE="${i#*=}"
+      shift # past argument=value
+      ;;
+    -b=*|--bits=*)
+      BITS="${i#*=}"
+      shift # past argument=value
+      ;;
+    -m=*|--mode=*)
+      MODE="${i#*=}"
+      shift # past argument=value
+      ;;
+    -p=*|--prediction=*)
+      PREDICTION="${i#*=}"
+      shift # past argument=value
+      ;;
+    -t=*|--prediction_type=*)
+      PREDICTION_TYPE="${i#*=}"
+      shift # past argument=value
+      ;;
+    -c=*|--clear=*)
+      CLEAR="${i#*=}"
+      shift # past argument=value
+      ;;
+    -*|--*)
+      echo "Unknown option $i"
+      exit 1
+      ;;
+    *)
+      ;;
+  esac
+done
+
+PARAMS_AS_STRING=""
+
+if [ -z "${SPECFILE}" ]; then               # Can't execute without specfile
+    echo "Specfile parameter is missing"
+    exit
+fi
+
+if [ -z "${LOGFILE}" ]; then               # Can't execute without logfile
+    echo "Logfile parameter is missing"
+    exit
+fi
+
+if [ -z "${BITS}" ]; then                   # Default number of bits per variable = 20
+    BITS=20
+fi
+
+PARAMS_AS_STRING+="--logfile ${LOGFILE} --bits ${BITS} "
+
+if [ -n "${MODE}" ]; then
+    PARAMS_AS_STRING+="--mode ${MODE} "
+fi
+
+if [ -n "${PREDICTION}" ]; then
+    PARAMS_AS_STRING+="--prediction ${PREDICTION} "
+fi
+
+if [ -n "${PREDICTION_TYPE}" ]; then
+    PARAMS_AS_STRING+="--prediction_type ${PREDICTION_TYPE} "
+fi
+
+
+echo "#### Given Arguments: ${PARAMS_AS_STRING}"
+echo "BDD bits per variable = ${BITS}"
 
 DEJAVU=`dirname $0`
+OUTPUT="output"
+echo "Working directory: ${DEJAVU}"
+echo "Output directory: ${OUTPUT}"
 
 # Parse specification and synthesize monitor:
-java -cp $DEJAVU/dejavu.jar dejavu.Verify $1 | grep -v "Elapsed total"
+java -cp $DEJAVU/dejavu.jar dejavu.Verify --specfile $SPECFILE --execution 1 | grep -v "Elapsed total"
 
 # Compile synthesized monitor:
 echo "Compiling synthesized monitor: ..."
-time scalac -cp .:$DEJAVU/dejavu.jar TraceMonitor.scala 2>&1 | grep -v "warning"
+time scalac -cp .:$DEJAVU/dejavu.jar $OUTPUT/TraceMonitor.scala 2>&1 | grep -v "warning"
 
 # Run the compiled monitor on trace:
 echo ""
 echo "Verifying trace: ..."
-time scala -J-Xmx16g -cp .:$DEJAVU/dejavu.jar TraceMonitor $2 $BDDSIZE $DEBUG 2>&1\
-  | grep -v "Resizing" | grep -v "load BDD package" | grep -v "Garbage collection"
+time scala -J-Xmx16g -cp .:$DEJAVU/dejavu.jar TraceMonitor $PARAMS_AS_STRING 2>&1\
+   | grep -v "Resizing" | grep -v "load BDD package" | grep -v "Garbage collection"
 
-# Clean up:
+
+# Cleaning Up:
+# ============
+if [ -n "${CLEAR}" ]; then
+   if [ "${CLEAR}"="1" ]; then
+       rm -rf $OUTPUT
+   fi
+fi
 rm *.class
